import type { Metadata } from "next";
import { Lato } from 'next/font/google';
import "./globals.css";
import React from "react";
import Providers from "@/components/layout/providers";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  display: 'swap'
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='es' className={`${lato.className}`} suppressHydrationWarning>
      <body>
      {/* <body className={'overflow-hidden'}> */}
        <Providers>
          <Toaster />
          {children}
        </Providers>
      </body>
    </html>
  );
}
